import Head from 'next/head';
import React from 'react';

function HomeMain() {
  return (
    <div className="bg-gradient-to-r from-black to-gray-800">
      <Head>
        <title>Content-WatchDog</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="flex items-center text-white w-full min-h-screen">
        <div className={`w-full h-full inline-block z-0  -mt-64`}>
          <div className="text-center">
            <span className="title-word title-word-1 text-8xl font-bold">
              Content-
            </span>
            <span className="title-word title-word-2 text-8xl font-bold">
              WatchDog
            </span>

            <p className="mt-4 text-xl underline">
              Safeguard Your Content with Content Watchdog API - Keeping NSFW in
              Check!
            </p>
          </div>
          <div className="text-center">
            <p className="m-7">Types of requests</p>
            <br />
            <h3 className="m-1">Text . Image . Video</h3>
          </div>
        </div>
      </main>
    </div>
  );
}

export default HomeMain;
